"""Generate a phased execution plan from spec analysis."""

import logging
from models import Phase, Task, GateConfig

logger = logging.getLogger(__name__)

# Standard phase definitions
PHASE_TEMPLATES = [
    {
        "id": "scaffold",
        "name": "Project Scaffolding",
        "description": "Initialize project, install dependencies, configure base settings",
        "gate_files": ["package.json", "tsconfig.json"],
        "gate_commands": ["npm install"],
    },
    {
        "id": "database",
        "name": "Database & ORM Setup",
        "description": "Set up database schema, ORM configuration, migrations",
        "gate_files": [],
        "gate_commands": [],
    },
    {
        "id": "auth",
        "name": "Authentication & Authorization",
        "description": "Implement user registration, login, session management, role-based access",
        "gate_files": [],
        "gate_commands": [],
    },
    {
        "id": "core-api",
        "name": "Core API & Business Logic",
        "description": "Build main API routes and business logic",
        "gate_files": [],
        "gate_commands": [],
    },
    {
        "id": "frontend",
        "name": "Frontend Pages & Components",
        "description": "Build UI pages, components, and layouts",
        "gate_files": [],
        "gate_commands": ["npm run build"],
    },
    {
        "id": "integration",
        "name": "Frontend-Backend Integration",
        "description": "Connect frontend to API, implement data fetching, forms",
        "gate_files": [],
        "gate_commands": ["npm run build"],
    },
    {
        "id": "testing",
        "name": "Testing",
        "description": "Write and run unit, integration, and e2e tests",
        "gate_files": [],
        "gate_commands": [],
    },
    {
        "id": "deploy",
        "name": "Deployment Configuration",
        "description": "Dockerfile, docker-compose, environment config, CI/CD",
        "gate_files": ["Dockerfile"],
        "gate_commands": [],
    },
]


def create_phase_plan(analysis: dict) -> list[Phase]:
    """Create a phased execution plan from spec analysis.

    Returns a list of Phase objects with gate configurations.
    Phases have no tasks yet — those are generated by task_generator.
    """
    tech = analysis.get("tech_stack", {})
    has_db = bool(tech.get("database"))
    has_auth = bool(tech.get("auth"))
    has_payments = analysis.get("has_payments", False)

    phases = []

    for template in PHASE_TEMPLATES:
        phase_id = template["id"]

        # Skip phases that don't apply
        if phase_id == "database" and not has_db:
            continue

        if phase_id == "auth" and not has_auth:
            continue

        # Build gate config
        gate_files = list(template.get("gate_files", []))
        gate_commands = list(template.get("gate_commands", []))

        # Add ORM-specific gate checks
        if phase_id == "database":
            orm = tech.get("orm", "")
            if orm == "prisma":
                gate_files.append("prisma/schema.prisma")
                gate_commands.append("npx prisma generate")
            elif orm == "drizzle":
                gate_files.append("drizzle.config.ts")

        # Add deployment gate
        if phase_id == "deploy":
            deployment = analysis.get("deployment", "")
            if deployment == "docker":
                gate_files.append("docker-compose.yml")
                gate_commands.append("docker build -t test-build .")

        phase = Phase(
            id=phase_id,
            name=template["name"],
            gate=GateConfig(
                file_checks=gate_files,
                command_checks=gate_commands,
            ),
        )
        phases.append(phase)

    # Add payments phase if needed
    if has_payments:
        payment_phase = Phase(
            id="payments",
            name="Payment Integration",
            gate=GateConfig(
                file_checks=[],
                command_checks=[],
            ),
        )
        # Insert after core-api
        api_idx = next(
            (i for i, p in enumerate(phases) if p.id == "core-api"),
            len(phases) - 1,
        )
        phases.insert(api_idx + 1, payment_phase)

    logger.info("Phase plan: %d phases", len(phases))
    for p in phases:
        logger.info("  - %s (%s)", p.name, p.id)

    return phases
